#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Runs unit tests
# $Id$
#
# Copyright ©2003-2007 Erik Grinaker <erikg@codepoet.no>
#
# This file is part of Revelation.
#
# Revelation is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Revelation is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from __future__ import absolute_import

import os
import sys
import types

sys.path.insert(0, "%s/.." % os.path.dirname(__file__))
sys.path.insert(0, "%s/../build/src" % os.path.dirname(__file__))

testsuites = []

if len(sys.argv) == 1:
	from tests.TestSuite import TestSuite

	testsuites.append(TestSuite)

else:
	try:
		for module in sys.argv[1:]:
			exec "from tests.%s import TestSuite" % module

			if type(TestSuite) is types.ModuleType:
				TestSuite = TestSuite.TestSuite

			testsuites.append(TestSuite)

	except ImportError:
		sys.stderr.write("Unknown test module %s\n" % sys.argv[1])
		sys.exit(1)

for testsuite in testsuites:
	testsuite().execute()

