#
# Revelation - a password manager for GNOME 2
# http://oss.codepoet.no/revelation/
# $Id$
#
# doc/SConscript - build configuration for SCons
#
# Copyright (c) 2003-2006 Erik Grinaker
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

Import("env")

# handle css
env.Install("$datadir/$package/doc/css", "file-specification/stylesheets/file-specification.css")

# handle images
images = []
images += env.PIC2Graph("file-specification/images/diagram-encryption.png", "file-specification/images/diagram-encryption.pic")
images += env.PIC2Graph("file-specification/images/diagram-fileformat.png", "file-specification/images/diagram-fileformat.pic")

env.Install("$datadir/$package/doc/images", images)

# handle file-specification xhtml
filespec_xhtml	= env.XSLTProc("file-specification/xhtml/index.html", env.Substitute([
	"file-specification/stylesheets/xhtml.xsl.in",
]) + [
	"file-specification/file-specification.xml",
])

env.Install("$datadir/$package/doc/xhtml", filespec_xhtml)


# handle file-specification xhtml-chunks
filespec_xhtmlc	= env.XSLTProc("file-specification/xhtml-chunks/index.html", env.Substitute([
	"file-specification/stylesheets/xhtml-chunks.xsl.in",
]) + [
	"file-specification/file-specification.xml",
])

filespec_xhtmlc += env.SideEffect([
	"file-specification/xhtml-chunks/accounttypes.html",
	"file-specification/xhtml-chunks/encryption.html",
	"file-specification/xhtml-chunks/xml.html",
], filespec_xhtmlc)

env.Install("$datadir/$package/doc/xhtml-chunks", filespec_xhtmlc)

