#
# Revelation - a password manager for GNOME 2
# http://oss.codepoet.no/revelation/
# $Id$
#
# doc/SConscript - build configuration for SCons
#
# Copyright (c) 2003-2006 Erik Grinaker
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

Import("env")

# handle file-specification xhtml
env.XSLTProc("file-specification/xhtml/index.html", [
	"file-specification/stylesheets/xhtml.xsl",
	"file-specification/file-specification.xml",
])

env.Command("file-specification/xhtml/css/file-specification.css", "file-specification/stylesheets/file-specification.css", Copy("$TARGET", "$SOURCE"))
env.PIC2Graph("file-specification/xhtml/images/diagram-encryption.png", "file-specification/images/diagram-encryption.pic")
env.PIC2Graph("file-specification/xhtml/images/diagram-fileformat.png", "file-specification/images/diagram-fileformat.pic")

# handle file-specification xhtml-chunks
env.XSLTProc("file-specification/xhtml-chunks/index.html", [
	"file-specification/stylesheets/xhtml-chunks.xsl",
	"file-specification/file-specification.xml",
])

env.Command("file-specification/xhtml-chunks/css/file-specification.css", "file-specification/stylesheets/file-specification.css", Copy("$TARGET", "$SOURCE"))
env.PIC2Graph("file-specification/xhtml-chunks/images/diagram-encryption.png", "file-specification/images/diagram-encryption.pic")
env.PIC2Graph("file-specification/xhtml-chunks/images/diagram-fileformat.png", "file-specification/images/diagram-fileformat.pic")

