#
# Revelation - a password manager for GNOME 2
# http://oss.codepoet.no/revelation/
# $Id$
#
# data/SConscript - build configuration for SCons
#
# Copyright (c) 2003-2006 Erik Grinaker
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

Import("env")

# handle bonobo files
bonobo = env.Substitute([
	"bonobo/GNOME_RevelationApplet.server.in",
])

# handle cracklib dictionary
crackdict = env.CracklibDict("cracklib/pwdict")

# handle gconf files
gconf = env.File([
	"gconf/revelation-applet.schemas",
	"gconf/revelation.schemas",
])

# handle icons
icons_16 = env.File([
	"icons/16x16/revelation.png",
])

icons_24 = env.File([
	"icons/24x24/revelation.png",
	"icons/24x24/revelation-locked.png",
])

icons_32 = env.File([
	"icons/32x32/revelation.png",
	"icons/32x32/revelation-locked.png",
])

icons_48 = env.File([
	"icons/48x48/gnome-mime-application-x-revelation.png",
	"icons/48x48/revelation.png",
	"icons/48x48/revelation-locked.png",
])

# handle mime data
mime = env.Substitute([
	"mime/revelation.desktop.in",
])

mime += "mime/revelation.xml"

# handle ui data
ui = env.File([
	"ui/menubar.xml",
	"ui/popup-tree.xml",
	"ui/toolbar.xml",
])

