# -*- coding: utf-8 -*-
#
# SCons build script
# $Id$
#
# Copyright ©2003-2007 Erik Grinaker <erikg@codepoet.no>
#
# This file is part of Revelation.
#
# Revelation is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Revelation is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

Import ("env")

# handle gconf schemas
env.InstallGConfSchema(env, "$gconf_schemadir", [
	"gconf/revelation.schemas",
])

# handle icons
env.Install("$datadir/icons/hicolor/16x16/apps", [
	"icons/16x16/revelation.png",
])

env.Install("$datadir/icons/hicolor/24x24/apps", [
	"icons/24x24/revelation.png",
	"icons/24x24/revelation-locked.png",
])

env.Install("$datadir/icons/hicolor/32x32/apps", [
	"icons/32x32/revelation.png",
	"icons/32x32/revelation-locked.png",
])

env.Install("$datadir/icons/hicolor/48x48/apps", [
	"icons/48x48/revelation.png",
	"icons/48x48/revelation-locked.png",
])

env.Install("$datadir/icons/hicolor/48x48/mimetypes", [
	"icons/48x48/gnome-mime-application-x-revelation.png",
])


# handle ui data
env.Install("$datadir/$package/ui", [
	"ui/menubar.xml",
])

