# -*- coding: utf-8 -*-
#
# SCons build script
# $Id$
#
# Copyright ©2003-2007 Erik Grinaker <erikg@codepoet.no>
#
# This file is part of Revelation.
#
# Revelation is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Revelation is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

Import ("env")

# handle scripts
scripts = env.Substitute([
	"revelation.in",
])

env.InstallScript(env, "$bindir", scripts)


# handle package
package_source = env.Substitute([
	"package/config.py.in",
]) + [
	"package/__init__.py",
	"package/dialog.py",
	"package/stock.py",
	"package/ui.py",
]

package = env.PythonBytecode(package_source)

env.Install("$python_libdir/$package", package_source + package)

